export const LEAGUES = {
    SPAIN: { id: 140, name: "La Liga", country: "Spain", code: "es" },
    SPAIN2: { id: 141, name: "La Liga 2", country: "Spain", code: "es" },
    ITALY: { id: 135, name: "Serie A", country: "Italy", code: "it" },
    FRANCE: { id: 61, name: "Ligue 1", country: "France", code: "fr" },
    PORTUGAL: { id: 94, name: "Primeira Liga", country: "Portugal", code: "pt" },
    BELGIUM: { id: 144, name: "Pro League", country: "Belgium", code: "be" },
    DENMARK: { id: 119, name: "Superliga", country: "Denmark", code: "dk" },
    GREECE: { id: 197, name: "Super League 1", country: "Greece", code: "gr" },
    TURKEY: { id: 203, name: "Süper Lig", country: "Turkey", code: "tr" },
    TURKEY2: { id: 204, name: "1. Lig", country: "Turkey", code: "tr" },
    POLAND2: { id: 107, name: "I Liga", country: "Poland", code: "pl" },
    ESTONIA: { id: 323, name: "Premium Liiga", country: "Estonia", code: "ee" },
    LITHUANIA: { id: 394, name: "A Lyga", country: "Lithuania", code: "lt" },
    MOROCCO: { id: 200, name: "Botola Pro", country: "Morocco", code: "ma" },
    EGYPT: { id: 233, name: "Premier League", country: "Egypt", code: "eg" },
    JORDAN: { id: 295, name: "Pro League", country: "Jordan", code: "jo" },
    CHILE2: { id: 266, name: "Primera B", country: "Chile", code: "cl" },
    // Previously existing
    AZERBAIJAN: { id: 31, name: "Premier League", country: "Azerbaijan", code: "az" },
    BULGARIA: { id: 71, name: "First League", country: "Bulgaria", code: "bg" },
    CROATIA: { id: 210, name: "HNL", country: "Croatia", code: "hr" },
    BOSNIA: { id: 315, name: "Premijer Liga", country: "Bosnia", code: "ba" },
    SLOVENIA: { id: 22, name: "Prva Liga", country: "Slovenia", code: "si" },
    POLAND: { id: 106, name: "Ekstraklasa", country: "Poland", code: "pl" },
    ROMANIA: { id: 283, name: "Liga I", country: "Romania", code: "ro" },
    CHILE: { id: 265, name: "Primera Division", country: "Chile", code: "cl" },
    COLOMBIA: { id: 239, name: "Primera A", country: "Colombia", code: "co" },
    ECUADOR: { id: 242, name: "Serie A", country: "Ecuador", code: "ec" },
    PERU: { id: 281, name: "Primera Division", country: "Peru", code: "pe" },
    URUGUAY: { id: 268, name: "Primera Division", country: "Uruguay", code: "uy" },
    PARAGUAY: { id: 252, name: "Primera Division", country: "Paraguay", code: "py" },
    CANADA: { id: 435, name: "Premier League", country: "Canada", code: "ca" },
    AUSTRALIA: { id: 188, name: "A-League", country: "Australia", code: "au" },
};

export const DEFAULT_ACTIVE_LEAGUES = [140, 31, 71, 210]; // Started with a subset as default
